---
title: 'Complete the square'
author: 'fnaufel'
email: 'https://fnaufel.github.io/'
date: '   (v. `r format(Sys.Date(), "%d/%m/%Y")`)'
lang: 'en'

output:
  # To install these output formats, run
  #   install.packages("devtools")
  #   devtools::install_github("fnaufel/fnaufelRmd")
  fnaufelRmd::html_report:
    []
---

```{r setup, include=FALSE}
# The next command configures MANY things and loads quite a few packages.
#
# If you want to see what's being done, execute
#
#   cat(
#     system.file(
#       "rmarkdown/resources/R/_common_report.R",
#       package = "fnaufelRmd"
#     )
#   )
#
# to find out the location of the file. Then open the file.
#
# If you want to change the configuration, copy the file, edit it, and
# source it instead of the package file.
#
# Or simply write your commands here in this code chunk.

source(
  system.file(
    "rmarkdown/resources/R/_common_report.R",
    package = "fnaufelRmd"
  )
)

library(reticulate)
sympy <- import('sympy')
py_run_string('from sympy import *')
py_run_string('from sympy.parsing.sympy_parser import T')
py_run_string('init_printing(use_latex = True)')
py_run_string('x, y = symbols(\'x y\')')

library(sympyglue)
```


# Complete the square

Make function to deal only with expression $ax^2 + cx$.

The function returns a list of expressions with the steps of the computation.

```{python}
def completesq(e, symb):
  
  # ax^2 + cx
  x = symb
  epoly = e.as_poly(x)
  
  a = epoly.coeff_monomial(x**2)
  c = epoly.coeff_monomial(x)
  
  # x^2 + cx/a
  terms_monic = monic(a*x**2 + c*x, x)
  
  # a * ( x^2 + cx/a )
  part = a * UnevaluatedExpr(terms_monic)
  
  # a * ( x^2 + cx/a + c^2/4a^2 ) - a * c^2/4a^2
  add_term = a * \
    ( \
      terms_monic + UnevaluatedExpr(c**2 / (4*a**2)) \
    ) \
    - a * UnevaluatedExpr(c**2 / (4*a**2))
  
  # a * ( x + c/2a )^2 - c^2/4a
  square = a * \
    ( \
      x + sign(c/a) * UnevaluatedExpr(abs(c) / (2*abs(a))) \
    )**2 \
    + -sign(a) * UnevaluatedExpr(c**2/abs(4*a))
  
  return [e, part, add_term, square]
```


A function to generate align from a Python list:

```{r}
align <- function(command, form = c('wide', 'narrow')) {
  
  py_run_string(
    paste0(
      '_steps = ', command
    )
  )
  
  form <- match.arg(form)
  
  if (form == 'narrow') {
    before <- paste0(
      '$$\n \\displaystyle \\begin{align} \n',
      '& ', m('{{_steps[0]}}'), '\\\\ \n'
    )
  } else {
    before <- paste0(
      '$$\n \\displaystyle \\begin{align} \n',
      m('{{_steps[0]}}'), ' '
    )
  }
  
  after <- '\n \\end{align} \n$$'

  middle <- m(
    '&= {{_steps[1:]}} '
  ) %>% 
    paste0(collapse = '\\\\ \n')

  m(paste0(before, middle, after, collapse = ''))

}
```

A function to run an example:

```{r}
eg <- function(expression, x = 'x') {
  
  py_run_string(
    paste(
      'expression = sympify(',
      expression,
      ')'
    )
  )
  
  x = as.character(x)
  command <- paste0('completesq(expression, ', x, ')')
  align(command)
  
}
```


## Numbers

```{r}
eg('2*x**2 + 3*x')
eg('2*x**2 - 3*x')
eg('-2*y**2 + 3*y', 'y')
eg('-2*y**2 - 3*y', 'y')
```


## Letters

```{r}
py_run_string('a, c = symbols("a c")')
eg('a*x**2 + c*x')
eg('a*y**2 + c*y', 'y')
```


